#!/usr/bin/expect -f

#trap sigwinch spawned
trap {
	set rows [stty rows]
	set cols [stty columns]
	stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

set machine [lindex $argv 0]
set screen  [lindex $argv 1]
set user gaowei08

switch -- $machine {
	""     { set machine gaowei08@cq01-rdqa-dev027.cq01.baidu.com }
	"d"    { set machine gaowei08@cq01-rdqa-dev027.cq01.baidu.com }
	"dev"  { set machine gaowei08@cq01-rdqa-dev027.cq01.baidu.com }
	"t"    { set machine work@yf-ps-beehive-test21.yf01 }
	"test" { set machine work@yf-ps-beehive-test21.yf01 }
	"hz"   { set machine gaowei08@hz01-ps-beehive-con0.hz01 }
	"nj"   { set machine gaowei08@nj02-ps-beehive-con0.nj02 }
	"sh"   { set machine gaowei08@sh01-ps-beehive-con0.sh01 }
	"tc"   { set machine gaowei08@tc-ps-beehive-con1.tc }
	"bj"   { set machine gaowei08@yf-ps-beehive-con0.yf01 }
}

switch -- $screen {
	"g" {set screen gaowei08}
	"b" {set screen beehive}
}

puts "machine: $machine"
puts "screen:  $screen"

set timeout 4
spawn ssh gaowei08@relay01.baidu.com

expect {
	"bash-baidu-ssl" { send "ssh $machine\n" }
	"password" { interact }
}

if {$machine != "gaowei08@cq01-rdqa-dev027.cq01.baidu.com" && $machine != "work@yf-ps-beehive-test21.yf01"} {
	send "export LS_COLORS='di=01;34'\n"
	send "cd /home/work\n"
}

if {$screen != ""} {
	send "screen -x $screen\n"
	expect {
		"no screen" {
			send "screen -S $screen\n"
		}
	}
}

interact

